server:
  port: 8080

# Oracle Connect
spring:
  datasource:
    url: jdbc:oracle:thin:@oracledb_high?TNS_ADMIN=C:\Oracle Wallet pad
    username: ADMIN
    password: Padoracle5day
    driver-class-name: oracle.jdbc.OracleDriver

  devtools:
    livereload:
      enabled: true

  # view Resolver
  mvc:
    view:
      prefix: /
      suffix: .html

# Mybatis
mybatis:
  config-location: classpath:configuration.xml
  mapper-locations: classpath:mappers/*.xml
