server:
  port: 8080

# Oracle Connect
spring:
  datasource:
    # url: jdbc:oracle:thin:@pad_high?TNS_ADMIN=C:\\OracleWalletPad
    # username: ADMIN
    # password: Padoracle5day
    # driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:mysql://localhost:3306/scottdb?serverTimezone=Asia/Seoul
    username: root
    password: mysql80
    driver-class-name: com.mysql.cj.jdbc.Driver

  # view Resolver
  mvc:
    view:
      prefix: /
      suffix: .html
      
# Mybatis
mybatis:
  config-location: classpath:configuration.xml
  mapper-locations: classpath:mapper/**/*.xml
