server:
  port: 8080

# Oracle Connect
spring:
  datasource:
    url: jdbc:oracle:thin:@pad_high?TNS_ADMIN=C:\\OracleWalletPad
    # url: jdbc:oracle:thin:@pad_medium?TNS_ADMIN=/Users/sung/Desktop/shortcut/Oracle/Oracle_wallet_PAD
    username: ADMIN
    password: Padoracle5day
    driver-class-name: oracle.jdbc.OracleDriver

  devtools: 
    livereload:
      enabled: true

  # view Resolver
  mvc:
    view:
      prefix: /
      suffix: .html

# Mybatis
mybatis:
  config-location: classpath:configuration.xml
  mapper-locations: classpath:mapper/**/*.xml
